# Generated by Django 4.2.5 on 2023-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kid_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_delivery_address', models.CharField()),
                ('second_delivery_address', models.CharField(blank=True, null=True)),
                ('city', models.CharField()),
                ('street', models.CharField()),
                ('building', models.CharField()),
                ('apartment', models.IntegerField()),
            ],
        ),
    ]
