services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"

  web:
    build: .
    command: >
      bash -c " python manage.py makemigrations && python manage.py migrate && python manage.py loaddata data.json && python manage.py create_default_superuser && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/app
      - static_value:/static/
      - media_value:/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db_data:
  static_value:
  media_value:
