# Generated by Django 4.2.2 on 2023-07-03 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='data/')),
                ('male', models.BooleanField(default=True)),
            ],
        ),
    ]
