# Generated by Django 4.2.7 on 2024-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='male',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Father'), (3, 'Mother'), (4, 'Babies')], default=0),
        ),
    ]
