# Generated by Django 4.2.2 on 2023-07-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_age_product_color_product_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('id',)},
        ),
    ]
