# Generated by Django 4.2.4 on 2023-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_color_country_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='letter_size',
            field=models.CharField(blank=True, choices=[('DOUBLE_EXTRA_SMALL', 'XXS'), ('EXTRA_SMALL', 'XS'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('EXTRA_LARGE', 'XL'), ('DOUBLE_EXTRA_LARGE', 'XXL')], default=None, null=True),
        ),
    ]
