# Generated by Django 4.2.4 on 2023-08-24 11:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='api.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='api.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_section', to='api.section'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chest_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waist_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arm_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('brand_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('insole_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('letter_size', models.CharField(blank=True, choices=[('XXS', 'DOUBLE_EXTRA_SMALL'), ('XS', 'EXTRA_SMALL'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA_LARGE'), ('XXL', 'DOUBLE_EXTRA_LARGE')], default=None, max_length=3, null=True)),
                ('country_size', models.CharField(blank=True, choices=[('Європа', 'Europe'), ('Англія', 'England'), ('Америка', 'America')], default=None, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='api.size'),
        ),
    ]
