# Generated by Django 4.2.4 on 2023-08-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_age_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
