# Generated by Django 4.2.4 on 2023-09-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_favorite_product_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RemoveField(
            model_name='size',
            name='age',
        ),
        migrations.RemoveField(
            model_name='size',
            name='arm_length',
        ),
        migrations.RemoveField(
            model_name='size',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='size',
            name='chest_size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='height',
        ),
        migrations.RemoveField(
            model_name='size',
            name='insole_size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='waist_size',
        ),
    ]
