# Generated by Django 4.2.4 on 2023-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_age_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
        migrations.AlterField(
            model_name='size',
            name='country_size',
            field=models.CharField(blank=True, choices=[('Europe', 'Європа'), ('England', 'Англія'), ('America', 'Америка')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='letter_size',
            field=models.CharField(blank=True, choices=[('DOUBLE_EXTRA_SMALL', 'XXS'), ('EXTRA_SMALL', 'XS'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('EXTRA_LARGE', 'XL'), ('DOUBLE_EXTRA_LARGE', 'XXL')], default=None, null=True),
        ),
    ]
