# Generated by Django 4.2.4 on 2023-09-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_country_remove_size_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.AddField(
            model_name='color',
            name='product_size',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='api.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='in_stock',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
