# Generated by Django 4.2.5 on 2023-09-27 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_country_remove_size_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', to='api.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', to='api.product')),
                ('product_size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='api.size')),
            ],
        ),
    ]
