# Generated by Django 4.2.4 on 2023-08-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_picture_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='product_image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
