# Generated by Django 4.2.4 on 2023-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='size',
            name='country_size',
        ),
        migrations.AddField(
            model_name='size',
            name='country_size',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='api.countrysize'),
        ),
    ]
