# Generated by Django 4.2.4 on 2023-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_product_product_size_color_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, related_name='product_sizes', to='api.size'),
        ),
    ]
