# Generated by Django 4.2.4 on 2023-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_country_remove_countrysize_name_countrysize_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, related_name='product_size', to='api.size'),
        ),
    ]
