# Generated by Django 4.2.4 on 2023-08-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
