# Generated by Django 4.2.4 on 2023-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='letter_size',
        ),
        migrations.AddField(
            model_name='countrysize',
            name='letter_size',
            field=models.CharField(blank=True, choices=[('DOUBLE_EXTRA_SMALL', 'XXS'), ('EXTRA_SMALL', 'XS'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('EXTRA_LARGE', 'XL'), ('DOUBLE_EXTRA_LARGE', 'XXL')], default=None, null=True),
        ),
    ]
