name: Check Code Style

on:
  push:
    branches:
      - main

jobs:
  check_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install ruff isort

    - name: Check code with ruff
      run: ruff check .

    - name: Check import order with isort
      run: isort .

    - name: Check for changes
      run: git diff --exit-code

    - name: Finish
      run: echo "Code style checks passed"
